/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'rentalPrice' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'available' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RentalRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const RentalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RentalRequestStatus,
  'borrowerEmail' : IDL.Text,
  'submittedAt' : Time,
  'bookId' : IDL.Nat,
  'borrowerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRentalRequests' : IDL.Func([], [IDL.Vec(RentalRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRentalRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateBookAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, RentalRequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'rentalPrice' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'available' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RentalRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const RentalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RentalRequestStatus,
    'borrowerEmail' : IDL.Text,
    'submittedAt' : Time,
    'bookId' : IDL.Nat,
    'borrowerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRentalRequests' : IDL.Func([], [IDL.Vec(RentalRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRentalRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateBookAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, RentalRequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };